services:
  tor-proxy:
    build:
      context: ./tor-proxy
    container_name: tor-proxy
    restart: always
    ports:
      - "9050:9050"
      - "9051:9051"

  postgres:
    image: postgres:16
    container_name: tor-postgres
    restart: always
    environment:
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawlerpass
      POSTGRES_DB: torcrawl
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  crawler:
    build:
      context: .
    container_name: tor-crawler
    depends_on:
      - tor-proxy
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    restart: always
